# Generated by Django 5.0.3 on 2024-04-08 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('shipping_address', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=60)),
                ('postalCode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=60)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
