# Generated by Django 5.0.3 on 2024-04-11 15:14

import django.db.models.deletion
import shipping_address.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('shipping_address', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='prefer not to say', max_length=50, validators=[shipping_address.models.stringValidation])),
                ('last_name', models.CharField(default='prefer not to say', max_length=50, validators=[shipping_address.models.stringValidation])),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=60, validators=[shipping_address.models.stringValidation])),
                ('postalCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='userAdresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='shipping_address.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
