# Generated by Django 5.0.3 on 2024-04-08 08:50

import shipping_address.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='first_name',
            field=models.CharField(default='prefer not to say', max_length=50, validators=[shipping_address.models.stringValidation]),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(default='prefer not to say', max_length=50, validators=[shipping_address.models.stringValidation]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=60, validators=[shipping_address.models.stringValidation]),
        ),
    ]
