# Generated by Django 5.0.3 on 2024-03-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("productname", models.CharField(max_length=150)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "productbrand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "productcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("productinfo", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock", models.IntegerField(blank=True, default=0, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
