# Generated by Django 5.0.3 on 2024-03-31 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_productcategory"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="productcategory",),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
        ),
    ]
