# Generated by Django 5.0.3 on 2024-04-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('cancelled', 'Cancelled')], default='Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
