# Generated by Django 5.0.3 on 2024-03-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Products", new_name="Product",),
    ]
