# Generated by Django 5.0.3 on 2024-04-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_numreviews"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"ordering": ["-createdAt"]},
        ),
        migrations.RemoveField(model_name="product", name="numReviews",),
    ]
