# Generated by Django 5.0.3 on 2024-03-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_productcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.category",
            ),
        ),
    ]
