# Generated by Django 5.0.3 on 2024-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_options_alter_product_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="numReviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
