# Generated by Django 5.0.3 on 2024-04-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_numreviews"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="numReviews",),
    ]
