# Generated by Django 5.0.3 on 2024-04-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_image_productimage_product_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="images",),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.DeleteModel(name="ProductImage",),
    ]
